/**
 * Bundle the API into a single CommonJS file that any Node host can run
 * directly — `node server-dist/app.js`, with no TypeScript and no build step
 * on the server.
 *
 * CommonJS, not ESM, because cPanel/Passenger runs the startup file with a
 * plain `require`, and ESM support there is inconsistent. The generated
 * server-dist/package.json pins the module type locally so the repository root
 * can stay "type": "module".
 *
 * Dependencies are bundled in. Shared hosting usually caps inodes, and
 * node_modules is tens of thousands of files — shipping one file avoids that
 * entirely, and means no `npm install` is needed on the server.
 */
import fs from 'node:fs'
import path from 'node:path'

const OUT_DIR = 'server-dist'

/*
 * Dependencies are the usual reason a deploy build fails: `git pull` brings in
 * a new one and `npm run build` is run without `npm install`. esbuild's own
 * error for that is a stack trace, so check first and say the useful thing.
 *
 * esbuild is imported dynamically below rather than at the top of this file: a
 * static import resolves before any of this runs, so a missing toolchain would
 * report ERR_MODULE_NOT_FOUND instead of the command that fixes it.
 */
const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'))
const missing = Object.keys(pkg.dependencies ?? {})
  .filter((name) => !fs.existsSync(path.join('node_modules', name)))

if (missing.length > 0) {
  console.error(`\n  Missing ${missing.length} dependency(s): ${missing.join(', ')}`)
  console.error('  Run "npm install" and build again.\n')
  process.exit(1)
}

if (!fs.existsSync(path.join('node_modules', 'esbuild'))) {
  console.error('\n  esbuild is missing — it is a devDependency, and npm skips')
  console.error('  those when NODE_ENV=production. Install them explicitly:\n')
  console.error('      npm install --include=dev\n')
  process.exit(1)
}

const { build } = await import('esbuild')

const result = await build({
  entryPoints: ['server/index.ts'],
  outfile: path.join(OUT_DIR, 'app.js'),
  bundle: true,
  platform: 'node',
  target: 'node18',
  format: 'cjs',
  sourcemap: true,
  minify: false, // keep stack traces readable — this runs on someone else's box
  logLevel: 'info',
  banner: {
    js: '/* MADOVA API — generated by scripts/build-server.mjs. Do not edit. */',
  },
})

if (result.errors.length) process.exit(1)

/* Node reads the nearest package.json for the module type. */
fs.writeFileSync(
  path.join(OUT_DIR, 'package.json'),
  JSON.stringify({ type: 'commonjs', private: true }, null, 2) + '\n',
)

const bytes = fs.statSync(path.join(OUT_DIR, 'app.js')).size
console.log(`\n  server bundle → ${OUT_DIR}/app.js  (${(bytes / 1024).toFixed(0)} kB, no runtime deps)`)
